{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.8/miuix-0.3.8.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-js-0.3.8.klib",
          "url": "miuix-js-0.3.8.klib",
          "size": 4232991,
          "sha512": "4fed9b38c2a8dd739bfa55fae40e4724fefa5770b51024a1178b9f1ea2a2620a8c1b54675550663d147ba4eeef09b51dafa0a1311b95ece14ecd357add5093d4",
          "sha256": "266a06a1fb8f9b3cc02e7c86a21147486d8b00216ac2ad1a7842f8ea24edb9bf",
          "sha1": "cde72ba7e43ad6f64b37ed1bdba6d55ef951a2d6",
          "md5": "d00c7f08c3d9456baa8164a015c89143"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-js-0.3.8.klib",
          "url": "miuix-js-0.3.8.klib",
          "size": 4232991,
          "sha512": "4fed9b38c2a8dd739bfa55fae40e4724fefa5770b51024a1178b9f1ea2a2620a8c1b54675550663d147ba4eeef09b51dafa0a1311b95ece14ecd357add5093d4",
          "sha256": "266a06a1fb8f9b3cc02e7c86a21147486d8b00216ac2ad1a7842f8ea24edb9bf",
          "sha1": "cde72ba7e43ad6f64b37ed1bdba6d55ef951a2d6",
          "md5": "d00c7f08c3d9456baa8164a015c89143"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "miuix-js-0.3.8-sources.jar",
          "url": "miuix-js-0.3.8-sources.jar",
          "size": 146100,
          "sha512": "7ec609971a13f9f428ea2070a8e33505fda980c8af666c030a275d0224f48f172f25015dabfa7df1fc490361532ce35fb33e974ff1bf6b1f068c81a7ab667b95",
          "sha256": "700bafe2250b46d793b36265b8c4ee425063a82cfb8d2b980a99cfeefa260134",
          "sha1": "08a9dac18d2275db22fcb87d1005449cbace15fc",
          "md5": "53431d49b0b005350af01cabfbe9a0f0"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.8.kotlin_resources.zip",
          "url": "miuix-js-0.3.8-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "bd391c864dc2fd90637c1c2f6864ca523c3a9fe9b97585fc71025c8fae0a3b300c48bf9049abb64ceafda8ab071d81dda7c6f9d2ef0e5b821f28bc05e7c1c1c7",
          "sha256": "95d87807361a6eed29c6adcfe112a8a2f2719db5e1d3bf5c42d99017ffb1bad5",
          "sha1": "d87c0c4a9735de244591a6c0fb4ff79897498d1d",
          "md5": "a832020157a1bb82b2686ae37e8187d5"
        }
      ]
    }
  ]
}
