{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.8/miuix-0.3.8.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.3.8.jar",
          "url": "miuix-desktop-0.3.8.jar",
          "size": 1026489,
          "sha512": "0687e8e44c2147e139b7ba5b3775fc3ced82e695172b1407f328aa02f2275a4148485f09bfef11ca953e2c8ecff4da7bf25e583dfb931d0f10c092f6b8b995a0",
          "sha256": "5abcb729cc722e6975eeb5be2f32e93f772c8b2d7a086b5107d193aa58bb1561",
          "sha1": "d325e38c1f8b623a4323154a31d2439fa96dfbd6",
          "md5": "6a52024f24488925d4281a57d075a43b"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.3.8.jar",
          "url": "miuix-desktop-0.3.8.jar",
          "size": 1026489,
          "sha512": "0687e8e44c2147e139b7ba5b3775fc3ced82e695172b1407f328aa02f2275a4148485f09bfef11ca953e2c8ecff4da7bf25e583dfb931d0f10c092f6b8b995a0",
          "sha256": "5abcb729cc722e6975eeb5be2f32e93f772c8b2d7a086b5107d193aa58bb1561",
          "sha1": "d325e38c1f8b623a4323154a31d2439fa96dfbd6",
          "md5": "6a52024f24488925d4281a57d075a43b"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "miuix-desktop-0.3.8-sources.jar",
          "url": "miuix-desktop-0.3.8-sources.jar",
          "size": 146217,
          "sha512": "04318a77774596b2ae2de26277e138363506b813fd69a46070103d59f183ddb09d7e70cfabd4cba02ec73bfcb38945b368d93fbad3c79af1bbcc95018c1dd71f",
          "sha256": "aaf5272bbf2dfbfc9e8c880dbab5449b66919d1c73fa2278ba703450513a3626",
          "sha1": "fab31969648abe2ef84f66d0a07765f33106b55c",
          "md5": "4d65ac26111fb0c0c9cebfb056e5e4a0"
        }
      ]
    }
  ]
}
