{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.7/miuix-0.3.7.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.3.7.jar",
          "url": "miuix-desktop-0.3.7.jar",
          "size": 1026482,
          "sha512": "796d2e1c548b2da857181b02e8c2ec48f3fbd393ebe529a4a3eb8fb5f9cd4a68fd2c6f99429cc05488d67ced26185c4d1f3b59244a546d94254f19444f03ee58",
          "sha256": "cbe6fa14e93424fa7225519888b13d4ea50f0bdd512c9a7500f2ea019448abbe",
          "sha1": "0fa5fbe6c8894bec908e9af470d505d5f98b69a0",
          "md5": "615f127fdc2910c1e2f7f46cf1d037d2"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.3.7.jar",
          "url": "miuix-desktop-0.3.7.jar",
          "size": 1026482,
          "sha512": "796d2e1c548b2da857181b02e8c2ec48f3fbd393ebe529a4a3eb8fb5f9cd4a68fd2c6f99429cc05488d67ced26185c4d1f3b59244a546d94254f19444f03ee58",
          "sha256": "cbe6fa14e93424fa7225519888b13d4ea50f0bdd512c9a7500f2ea019448abbe",
          "sha1": "0fa5fbe6c8894bec908e9af470d505d5f98b69a0",
          "md5": "615f127fdc2910c1e2f7f46cf1d037d2"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "miuix-desktop-0.3.7-sources.jar",
          "url": "miuix-desktop-0.3.7-sources.jar",
          "size": 146213,
          "sha512": "f2a23648fe87454ef634a5592949ce6bf0f954d680e333a1b8e86847ef8275e1938b2e7ac958766dfc92d3a79566d9ba00e3e64e39e415ca1656976c32e4a324",
          "sha256": "23c5124b982ee758fbc0275999788568f5af40b5f766cb8c3535fc1f61c748da",
          "sha1": "3107e80df77d2ec624d0890c11822e273eee5858",
          "md5": "20c38ff09578b7f1f7eb0289a57cd184"
        }
      ]
    }
  ]
}
