{
  "formatVersion": "1.1",
  "component": {
    "url": "../../haze/1.6.0-SNAPSHOT/haze-1.6.0-SNAPSHOT.module",
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "haze-release.aar",
          "url": "haze-android-1.6.0-SNAPSHOT.aar",
          "size": 184505,
          "sha512": "41f0e14ef1f0001c540e24dd90bd0c7ec09cf28430feaab683ba7e5ba2355e40fb51e7d42b87ac88d9d7d5b50fd5328167e782038a8d264679061dcf0c430c5a",
          "sha256": "979d3aeeef7dd1a64538ab7b7171651ad5490a01da450535055d7c78029561a3",
          "sha1": "f1ced5b3b284808c695976cd97dc3d69cde8c768",
          "md5": "60176265617eeb0833f297bb6037f7f6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "haze-release.aar",
          "url": "haze-android-1.6.0-SNAPSHOT.aar",
          "size": 184505,
          "sha512": "41f0e14ef1f0001c540e24dd90bd0c7ec09cf28430feaab683ba7e5ba2355e40fb51e7d42b87ac88d9d7d5b50fd5328167e782038a8d264679061dcf0c430c5a",
          "sha256": "979d3aeeef7dd1a64538ab7b7171651ad5490a01da450535055d7c78029561a3",
          "sha1": "f1ced5b3b284808c695976cd97dc3d69cde8c768",
          "md5": "60176265617eeb0833f297bb6037f7f6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "haze-android-sources.jar",
          "url": "haze-android-1.6.0-SNAPSHOT-sources.jar",
          "size": 41408,
          "sha512": "7ca295a39f17c6ecc220f53658761d2c5b6dc986757d8c9cec6d56de0ea85a3e7c7f2439568cffb59d99418bd9142c7f0845c0b9c1ca376bc551a32e673d72ba",
          "sha256": "92da697e93609cca68c23acbe8601c5bfbbf69d8acb27db5995aff17e5711460",
          "sha1": "f50334358f3d81c5f80a6d78d048c9065448ad6c",
          "md5": "4024e392c5b286b1e7e245f7c48509f3"
        }
      ]
    }
  ]
}
