{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.4.0/miuix-0.4.0.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosArm64Main-0.4.0.klib",
          "url": "miuix-iosarm64-0.4.0.klib",
          "size": 800350,
          "sha512": "e35cdd2f94fb3d4006b3ab42ea582af16f7aa2e1f8d340390dd3ccd132c5f8ad587f8605c650f769572c048d27d83d2bdff0ce4a4ec735b01c6e04f93b9eb003",
          "sha256": "8cf2cf6688fb03bb53ac85543eeb310bc033601017f6cbe39aef09c420818e8f",
          "sha1": "105f18025cc2f9d49e9bb580b619e30256eaa33d",
          "md5": "b2413aaccb4b83af4262509c49a52fbe"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosarm64-0.4.0-sources.jar",
          "url": "miuix-iosarm64-0.4.0-sources.jar",
          "size": 146542,
          "sha512": "3d3506e16b27b890d100e96db4de7e071cda7c6ccdf680c84054b00e0629231f111738c3e57b36188aba9a0d7ead0bde6bed57601165a6246ef76c39fb3fafca",
          "sha256": "ed8a9c12cc976a03d32d842caa530d1d8ea8f9b99a673898378dc92192b4688c",
          "sha1": "22109a6836edaa4a2d695f7879dcc58b497cebf8",
          "md5": "631d22ecfb6ea87d6d9d7c42afbec4c2"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.4.0.kotlin_resources.zip",
          "url": "miuix-iosarm64-0.4.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "5ab2b6529910e756f0648a01d5c567f3f38b827ca56c1218d2db6b79598bdff77e2732df94bf05d7b7c9febb81b9600ce7fe1da41b9266da6e3422ef4a60ae08",
          "sha256": "ef333e8c80fc47f4ffcaaf5aaad9872344dd1b8f78b24c4e1a24fdbcdf9a8b41",
          "sha1": "0b3957d480f8653557209c59379c633512befd5b",
          "md5": "10437152545914a2f7b92328a6cbac4f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosarm64-0.4.0-metadata.jar",
          "url": "miuix-iosarm64-0.4.0-metadata.jar",
          "size": 5208,
          "sha512": "2b9ca9d27a05192ec8aca5c59c7c3f177f8ce88b879e0f1ea1d4845fa38f6111eb46b908be1f50017e67ef28564d6203b46dadd2c31907199e04cce46dec5359",
          "sha256": "1187848ef829b28e0b74fcbec789d75df994986367dc2f419accf945e8433190",
          "sha1": "9c0a3dbf8945c687aa9392d6a6585fd936d3f7bd",
          "md5": "31e41c761c8eaab5d75b46449452c845"
        }
      ]
    }
  ]
}
