{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.8/miuix-0.3.8.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-macosArm64Main-0.3.8.klib",
          "url": "miuix-macosarm64-0.3.8.klib",
          "size": 806582,
          "sha512": "713c13a0374c64c884fa4371cb2380420146e02870aad5ae3a6ccfe03a2d4e325c84a72862bc130e56e154b6a74ea47f77cd9695ecf209b6113829f5bd211657",
          "sha256": "e1d3745772103cbd2672dc597a75f2a9c97f5cde57695b93cdaae86c6b0d6864",
          "sha1": "68668727bea04abd07cc06413ed76b80d8672298",
          "md5": "d8abbc7f0d8e2017e9aa9f316297414f"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-macosarm64-0.3.8-sources.jar",
          "url": "miuix-macosarm64-0.3.8-sources.jar",
          "size": 146923,
          "sha512": "cf80f803a1c069ce00839906fbbb25ef70b5c133857e72ec321d5494d4f01abec5178e2fb317775d9a79b30bce8a705e74a9aebcffbf3592b14f3f311612a066",
          "sha256": "56a62a45dec1a035552340fa8d6ffcc369b93e363a903b735e99e6285d5b573c",
          "sha1": "392aeb181001937ad2ace3b2585ec93847188d8a",
          "md5": "977a8f888b676b633a43736aec202751"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.8.kotlin_resources.zip",
          "url": "miuix-macosarm64-0.3.8-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "f624b604c72be3509965f6db108c2d862bb2110a262af249ba3f6a0833a8a04210da69e5d58c7093f8e7786e10f1457b9fd6c3448b629e442ef8e691a3ef574f",
          "sha256": "bb91867899f09e03e86078567c8de7df7773700e5990c2fd76b70244eba0201a",
          "sha1": "163e0bea96cd344c61bcbc9a437949bcd1203610",
          "md5": "b18e3c5efdc8328c81736ad1a4b4f868"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-macosarm64-0.3.8-metadata.jar",
          "url": "miuix-macosarm64-0.3.8-metadata.jar",
          "size": 5208,
          "sha512": "9314591da0cd9c1e930f9ed42adf62338d65637158877161faaaf71e56b68619cebd11bc2a1ab391b8835ff0baaec9ae6af49f013094556ff67f9e7f529aa236",
          "sha256": "77a05f5c1f1bdd60ed0f1b413a4a09ad9a5a3dd67f25241cf8f1074992e029c0",
          "sha1": "4219eac7369c2cdf80e735669071736a93bfe2f8",
          "md5": "c6987223d0ecb153ea3a3dca8a2dfe17"
        }
      ]
    }
  ]
}
