{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.4.0/miuix-0.4.0.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosSimulatorArm64Main-0.4.0.klib",
          "url": "miuix-iossimulatorarm64-0.4.0.klib",
          "size": 800443,
          "sha512": "e30c896c51ccfd36d880268d800a2850726dd957cb2900bab4776d1c813cfecd5193aab5407b452324c47d534869d6189ea501da5feed5407f284e9081c2dac9",
          "sha256": "14fbc0be9bcdaa9bc11080f3912b9b333fa99c89350c15e71f2672a781bb2e42",
          "sha1": "0ff9d7c7a567234edaa222c0014d9e31678814c8",
          "md5": "bfa9d841e6a9bb9d23fd935435e4eb05"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iossimulatorarm64-0.4.0-sources.jar",
          "url": "miuix-iossimulatorarm64-0.4.0-sources.jar",
          "size": 146704,
          "sha512": "995dcfe239d427e8bd1b8f48f52d59c325e7c7720bd1069a48aca3c649c941a19339e7b9721a0cd7d7f73d5695ae795bdf3cd0ac59f563093e91c83c1b2f4e24",
          "sha256": "9f975cf508fd1e568b93de89ce74af11de0cab3d1ae0c6c670c700cac72a3aa7",
          "sha1": "7114c2fc1423d792e0890b2ca2dba1c70ed22ad8",
          "md5": "4a9f233f5e99fad79efef516bf22d916"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.4.0.kotlin_resources.zip",
          "url": "miuix-iossimulatorarm64-0.4.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "eb00182427e583e8ac244562c095b6fc3353dad0aa5c1af9f2970040d3a6ea8ea85176163e9e4298511118ecfdd31e818fec91564d61c6973b9b0f699ed344e2",
          "sha256": "9c75f517ddc2fcc89f30e828cc10be04534b8eb22bc60f9be184a1b3a46acc2b",
          "sha1": "0a6a72c6eebc95304342289759e67fe2dc5280ee",
          "md5": "a0d9cf61ec825208dba79bb6c5dbbfbb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iossimulatorarm64-0.4.0-metadata.jar",
          "url": "miuix-iossimulatorarm64-0.4.0-metadata.jar",
          "size": 5208,
          "sha512": "ea544b034f0e0c893d2cc9a74981ef7986899498968f78507b8b7837cb7b4f363055dabe1582f3d4e451216ab32d11a48b9b6156b62b5241a9cea4986943b687",
          "sha256": "7c3c54fb6d42697feaf27bd4e64b0fa175594e9f640c5453f8146d22b984df9f",
          "sha1": "146623e9952b073c5887fb9cfced9be4c3c3d06d",
          "md5": "e653de08957b5c715a7cf954bbaac779"
        }
      ]
    }
  ]
}
