{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.4.0/miuix-0.4.0.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-macosArm64Main-0.4.0.klib",
          "url": "miuix-macosarm64-0.4.0.klib",
          "size": 800877,
          "sha512": "c397628e6a46cd9121acabfad1a1846fd551c4655053a2e2cb2511230fb83683ab7452bfcf3b471fe2c721715f81bbda12e9698e85f1769f953b057a2111949c",
          "sha256": "a0af17b5f5ab6edc457af5211271ffd4eaef60e2cc2e929577151fc0b82daaa5",
          "sha1": "720ee0da8350a18804513ae93cde7f684d8d5a6d",
          "md5": "9018d4fb158b408e0843ace1708b19f7"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-macosarm64-0.4.0-sources.jar",
          "url": "miuix-macosarm64-0.4.0-sources.jar",
          "size": 146680,
          "sha512": "2c6368e22f0ec5918eb123d57edcc7e61778cd96cd7728094970de6c78c2ddd00e2d83b5c5acd768d9afd6d27094c9f1f8e48fd528b75cd5883f5ccc5d3a86b7",
          "sha256": "ec0dec1496f5c4739bbf5dedde0b1f648c14361e243d83e5e30777390b4fca9a",
          "sha1": "51a984168b762f0277e87ec61ecf962a0622bea6",
          "md5": "0c39cec3bfb4159d3bd95f1af697a21f"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.4.0.kotlin_resources.zip",
          "url": "miuix-macosarm64-0.4.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "7e3e416262abb262e02f84e3df49325b2c5816049b586f62b0da70420e31d5a4958790287af2d19ea61d758221079bd965478b97f6d49508d77cbded3d3aab72",
          "sha256": "1d9d2eeeb6ea62e2abf8e45f788dd6fd09d71e7543ade2507986879372ca2901",
          "sha1": "2cc84158366d20d5d7921b857e0f66238f07195a",
          "md5": "e0c45713b1ede312c5209d8ea2dfc417"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-macosarm64-0.4.0-metadata.jar",
          "url": "miuix-macosarm64-0.4.0-metadata.jar",
          "size": 5208,
          "sha512": "266b600a384d7c40c2214cc9fc64e055c32904e13fdf441b97b4fae23d46e8ad4c1863f06a9e36124950a8bbe6d0caf417b7857705b86702a43604e1d4d504b1",
          "sha256": "f3b163f21d70ffa562d42def466159db0585a9f578410b901d574f5d424653dd",
          "sha1": "9c184cebc497ad88e9cb49b05ef41f3a5f316df7",
          "md5": "b6567276fb7e8bb9d2be597ff243a0fc"
        }
      ]
    }
  ]
}
