{
  "formatVersion": "1.1",
  "component": {
    "url": "../../haze/1.6.0-SNAPSHOT/haze-1.6.0-SNAPSHOT.module",
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-iosSimulatorArm64Main.klib",
          "url": "haze-iossimulatorarm64-1.6.0-SNAPSHOT.klib",
          "size": 178338,
          "sha512": "bd44b5c62b371aef3d7005ac9a5a26b11174042f32531747517e7166340b842f0c703738276d3404903ba4f080b3df8d8382d8155bbffb9ebcda866376fab725",
          "sha256": "864cdb4b0b8b1584941bd20c75237e62e01c15cb0ce245f5169b32a30b766eee",
          "sha1": "5ff528936375294483570acb53d74598fe88a19f",
          "md5": "4c5b3911420923d782b2998b9b107848"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "haze-iossimulatorarm64-sources.jar",
          "url": "haze-iossimulatorarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 36509,
          "sha512": "976d09b7883df7c8cfe53a495c1c4fcb9afda75c42b21de763a3b7f68615db44f0781ebf950e94f23a589946c0e6294ae73851603bbe8b90d5120aee7d57979e",
          "sha256": "355c5117655a10a449b2c9597969f4f0a55f45fad40b8771d8b3bd42d1ff24fa",
          "sha1": "b638f3dff46a976cbd827346b84d045942780c3b",
          "md5": "7049ecd1946b281a0bc9042a90313137"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze.kotlin_resources.zip",
          "url": "haze-iossimulatorarm64-1.6.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 316,
          "sha512": "bf7fe1a2682dc22ca4b9262d0e29fb1cfb1f2e2c89a4f8e6ecd2034dc8b3491a964969df67c418ff6be0840719d24bce61ea6bd757cc898f54add7adac8f2818",
          "sha256": "f28247f44cce1ca5c28d277dc0996346957424520c29b9ce92cb4daa3f96223a",
          "sha1": "f520652ad156e4a8f824b40079cdabf9abc07caa",
          "md5": "57305aeee4cf6e1a1b4b5d85ad6be641"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-iossimulatorarm64-metadata.jar",
          "url": "haze-iossimulatorarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 2856,
          "sha512": "14b92db9065861cb6cb5cf4e6beeab8570422d6ff6288612039b5098dbddd626ede9cead58407c43f859a03ff787a0e578f3128006fec5b031bb1a9a6872b7b6",
          "sha256": "a2191b2b3837eb92a201a39d2c7f163c8b1707f77ee29433c6c38816267a4c30",
          "sha1": "ac33e7c80895b3e0f4b55069c904e08daf793144",
          "md5": "876803eb4b17bf8766d618e790c41fe7"
        }
      ]
    }
  ]
}
