{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.6/miuix-0.3.6.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.3.6.jar",
          "url": "miuix-desktop-0.3.6.jar",
          "size": 1031820,
          "sha512": "50045e1ee2cc33410d7c88e443d44650c0aafc7c0159482981a848ab802792120ed665fab436cf866b455c4f4880304d794a4afe2f14a7dc27bcacdd2f5e658e",
          "sha256": "b8cb8d522bb6e555538d93fc68cfaf8c9b1ee9479dd91dd56a8b485d79a96430",
          "sha1": "65da9610c0bad73991bebed588bcb09e247ce0d4",
          "md5": "f351f4f63bbe6bb9431c278e6620bf3f"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.3.6.jar",
          "url": "miuix-desktop-0.3.6.jar",
          "size": 1031820,
          "sha512": "50045e1ee2cc33410d7c88e443d44650c0aafc7c0159482981a848ab802792120ed665fab436cf866b455c4f4880304d794a4afe2f14a7dc27bcacdd2f5e658e",
          "sha256": "b8cb8d522bb6e555538d93fc68cfaf8c9b1ee9479dd91dd56a8b485d79a96430",
          "sha1": "65da9610c0bad73991bebed588bcb09e247ce0d4",
          "md5": "f351f4f63bbe6bb9431c278e6620bf3f"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "miuix-desktop-0.3.6-sources.jar",
          "url": "miuix-desktop-0.3.6-sources.jar",
          "size": 146971,
          "sha512": "3343254b35ecbe5e694f33120ecc289cb4fd32317befc09abcf5b6f1ef84a323d638b0c71d3dfaf86ce0cd4278027734eee7e9233938275f148a633abc6decee",
          "sha256": "db6760d276e2e6c803d22f1507f79fa3e5ada4bf2062f193c04f2c485c5b8df6",
          "sha1": "11148126f1ef999d358933ae41256adbbe3efe66",
          "md5": "fd59aff332fb6535427bae1d6bd2fd46"
        }
      ]
    }
  ]
}
