{
  "formatVersion": "1.1",
  "component": {
    "url": "../../haze/1.6.0-SNAPSHOT/haze-1.6.0-SNAPSHOT.module",
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "haze-jvm.jar",
          "url": "haze-jvm-1.6.0-SNAPSHOT.jar",
          "size": 148325,
          "sha512": "f38846f77826cde89dac8d94942b229c4bd24c7137b9934236dff9351e768b6bf1e522fc38092fba5caa58914d8b6ce6cde06fcfee543ac4403a225f4b83f4f5",
          "sha256": "8759599ba5947187a6b37ec86ccfa2b11a02f584170af4629d7e6e30b91c88b4",
          "sha1": "c50b2ee58948d6db6ef7627a72c0f261bc3842ab",
          "md5": "cc9c3b67cc487b1343e22820a1acff95"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-jvm.jar",
          "url": "haze-jvm-1.6.0-SNAPSHOT.jar",
          "size": 148325,
          "sha512": "f38846f77826cde89dac8d94942b229c4bd24c7137b9934236dff9351e768b6bf1e522fc38092fba5caa58914d8b6ce6cde06fcfee543ac4403a225f4b83f4f5",
          "sha256": "8759599ba5947187a6b37ec86ccfa2b11a02f584170af4629d7e6e30b91c88b4",
          "sha1": "c50b2ee58948d6db6ef7627a72c0f261bc3842ab",
          "md5": "cc9c3b67cc487b1343e22820a1acff95"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "haze-jvm-sources.jar",
          "url": "haze-jvm-1.6.0-SNAPSHOT-sources.jar",
          "size": 36410,
          "sha512": "653c7b122be76a3311bd50728b0a64bfb72068969236dd254a37e02109396d0d606b732ff6b49f54e5e0fa5458028fb3c746959c6596dc5182fdfec415904912",
          "sha256": "191f556b73ef50499ab1f6680710e682f32c3b19ff628794abba48f9434f7cc9",
          "sha1": "d44e1d4a46af0e7504a95f263eccec3c7cecf5f2",
          "md5": "707d3304fe80fff058f039a09e8bac3f"
        }
      ]
    }
  ]
}
