{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.7/miuix-0.3.7.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosSimulatorArm64Main-0.3.7.klib",
          "url": "miuix-iossimulatorarm64-0.3.7.klib",
          "size": 806117,
          "sha512": "bdfa042f31a60fa68e93586eef08ae72cdf856132a88cea071002be659a86c8813ee888afec4355b34001a447e796ebd1d4c4ba8a0c2fff307c2178830098b06",
          "sha256": "079de0d85cb40500bf04911f52558f3bd30e189465e7be950b13398a8100be92",
          "sha1": "15ace561e382d835913864b9896829a22482d53d",
          "md5": "1de6818349e74a4335bfa2f83e6c9034"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iossimulatorarm64-0.3.7-sources.jar",
          "url": "miuix-iossimulatorarm64-0.3.7-sources.jar",
          "size": 146943,
          "sha512": "37a79e1f77cedc5a184101d60d444fd8d70c6abc4f23c22efecf679d40f86bedaee53b1081463fd1111d55eec902f313082e5f727ab0b6c2ba894658729cffb3",
          "sha256": "33f434cfa187612da2015ba6b7ab60d03fc0a9b821d9a44e8c1cefa7dcd684a6",
          "sha1": "aa6dee810532e55c0e88816c8f9567a8df88d6e1",
          "md5": "c06a5aa7f862afad1d20051354c30e1a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.7.kotlin_resources.zip",
          "url": "miuix-iossimulatorarm64-0.3.7-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "60ea90a30ab9ffea29eee8e85c2fe7a6912ed3eac57774d950884cd977611b0712571c69362bb09f561680f9598b53e51a7e0793402b294f4c90b2a5b52edc79",
          "sha256": "e5d6cf6a099a4d6e89a9f1f850b9b76f56bfe3fcf3bdcb8ca99a668cd9c97ed0",
          "sha1": "c4b4814eb605914539e25bc1a0133f7ff506258c",
          "md5": "95c637a06e8f6f98b09272dae2db7df8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iossimulatorarm64-0.3.7-metadata.jar",
          "url": "miuix-iossimulatorarm64-0.3.7-metadata.jar",
          "size": 5208,
          "sha512": "747d0498238971614941341af423d529b05465e43bb52c831c17b0a7a620289a6ef7f7e92a00a4069d1aa5468c8144b684e75f2f577bc4b2961dab695ea93d60",
          "sha256": "a9149b50a0494e78fc0b851dcd7482051213e0cfcd2a55e51a5848b3be0ae439",
          "sha1": "0bafbf591513aac6cb2e5be842398c444c147103",
          "md5": "2787fc6a0b84033c1c149f0ea6a4283d"
        }
      ]
    }
  ]
}
