{
  "formatVersion": "1.1",
  "component": {
    "url": "../../haze/1.6.0-SNAPSHOT/haze-1.6.0-SNAPSHOT.module",
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-macosArm64Main.klib",
          "url": "haze-macosarm64-1.6.0-SNAPSHOT.klib",
          "size": 178255,
          "sha512": "bfd0c8ef40376b9966e251bdf8da42864a2a52f4ab968bbc1089b4922e2a93e1e0b3d6339ea20a32b16d36d49cde589a4577e4bd991988fb9ac1932d704a2408",
          "sha256": "a3c507ea30ef52fa075945d7a0e10af3db4a566f24a4034e7e64d7e95cb1d506",
          "sha1": "0325a554dbf073f3c53c598ad59ce1beda1d6949",
          "md5": "415015034a98bc4d5d510b340197870a"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "haze-macosarm64-sources.jar",
          "url": "haze-macosarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 36509,
          "sha512": "976d09b7883df7c8cfe53a495c1c4fcb9afda75c42b21de763a3b7f68615db44f0781ebf950e94f23a589946c0e6294ae73851603bbe8b90d5120aee7d57979e",
          "sha256": "355c5117655a10a449b2c9597969f4f0a55f45fad40b8771d8b3bd42d1ff24fa",
          "sha1": "b638f3dff46a976cbd827346b84d045942780c3b",
          "md5": "7049ecd1946b281a0bc9042a90313137"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze.kotlin_resources.zip",
          "url": "haze-macosarm64-1.6.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 316,
          "sha512": "e0d1e3557c8b5dfac99ba7b9d732f6f400ee9ac252240cba6fdfa22b70dc46fef2a2f9f5964c76d2a0952554b4dba01adfa4a60e7143066cacdff20dd6ebfdad",
          "sha256": "6cc8e24a3b24746dd7b474dfb4f206e08fe111b7d20d2b5a22a1ab168c3ad1c0",
          "sha1": "85c330b7c78b359b634cfe9a59141005017518be",
          "md5": "8441a50b2b706954ecd573871d91d59e"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-macosarm64-metadata.jar",
          "url": "haze-macosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 2856,
          "sha512": "14b92db9065861cb6cb5cf4e6beeab8570422d6ff6288612039b5098dbddd626ede9cead58407c43f859a03ff787a0e578f3128006fec5b031bb1a9a6872b7b6",
          "sha256": "a2191b2b3837eb92a201a39d2c7f163c8b1707f77ee29433c6c38816267a4c30",
          "sha1": "ac33e7c80895b3e0f4b55069c904e08daf793144",
          "md5": "876803eb4b17bf8766d618e790c41fe7"
        }
      ]
    }
  ]
}
