{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.7/miuix-0.3.7.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.3.7.klib",
          "url": "miuix-wasm-js-0.3.7.klib",
          "size": 809071,
          "sha512": "5559be3f57e1880736963b44fbd439baad23288db9b47366885c777605e8dc8cb122c1296e384f2df5c8e3da0cd4766394077c10f4ce69a516d080b71854358d",
          "sha256": "cea1062a4c584f940e780478206ac3f61e5cf1c9e73beece9946c2e50df717a2",
          "sha1": "7f738bce949be53794623517b131214255f52b66",
          "md5": "871d8dce79f122a17664ff3d613576d6"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.3.7.klib",
          "url": "miuix-wasm-js-0.3.7.klib",
          "size": 809071,
          "sha512": "5559be3f57e1880736963b44fbd439baad23288db9b47366885c777605e8dc8cb122c1296e384f2df5c8e3da0cd4766394077c10f4ce69a516d080b71854358d",
          "sha256": "cea1062a4c584f940e780478206ac3f61e5cf1c9e73beece9946c2e50df717a2",
          "sha1": "7f738bce949be53794623517b131214255f52b66",
          "md5": "871d8dce79f122a17664ff3d613576d6"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "miuix-wasm-js-0.3.7-sources.jar",
          "url": "miuix-wasm-js-0.3.7-sources.jar",
          "size": 146202,
          "sha512": "edb7a60dc92cf23e67d0c92c4b515b68c52fefdaff2043827cacad67dad74068d91bc1be563784153a56f6fad82d26ac95fbeca01f3c19b3072b0debbc5ce0ce",
          "sha256": "32231091baa6b617ee7e6cfa24992aa898ba18e79593c0bf49064c54684f72d4",
          "sha1": "de412b31c816843401990ad230c9147b7da8bcf6",
          "md5": "138dc7cd6b717914ea471143db62e3f8"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.7.kotlin_resources.zip",
          "url": "miuix-wasm-js-0.3.7-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "71af6e6274688a63da18a5645ac254fc895878cd413db083b2fafb97c45cadccd968ea19b834febe506715c382be651113b27dc2f292d1fe4cbda7ce7cc41b2b",
          "sha256": "884e57c1c214f538716d2b2a9d46b1dca2cf36d2ee7a53e7d3af0b3ca88f77c0",
          "sha1": "ae42d22cfe8debf0afbab823a62587adadd71cb4",
          "md5": "fc9487ef692a2995c984d60542472d5d"
        }
      ]
    }
  ]
}
