{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.8/miuix-0.3.8.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosX64Main-0.3.8.klib",
          "url": "miuix-iosx64-0.3.8.klib",
          "size": 806037,
          "sha512": "153309cf912862438987b224d4a146ee677a3802317429f7a73d156af54f77e4e6bcb681cb91c1f989d8cd83ad030847986517c1739d7c7db54e8f91bd122d17",
          "sha256": "7a128c3f8e450d94f6533569e76e4eec7cc2b1055d6f4b666df85471af7f1bad",
          "sha1": "54d3be0ad8afd28a292e90b472c382857a922abf",
          "md5": "38654b09926fa988749412e123d05a01"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosx64-0.3.8-sources.jar",
          "url": "miuix-iosx64-0.3.8-sources.jar",
          "size": 146749,
          "sha512": "d0e9f4fe555a1148098f1c59364f6d959e131e8f1bc3825d4cd6b2154011f43f98a33b6bc199f4966d17cce1a2ca7012109d33149d360f478a5ec0ccd154e8bd",
          "sha256": "a45104d09a2796c20498dddc44d22efe81b634d1f6d41aa7072faeb9713af74f",
          "sha1": "d7de901dadfd6f6e1fb5d9715e309bfb64fde4cf",
          "md5": "872a5b52e082b783b90b9653020d8eff"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.8.kotlin_resources.zip",
          "url": "miuix-iosx64-0.3.8-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "06bb4272a0d4e02556f4e63dccc18421adeb10645c1cddf106fbcdba93049e721a78d18b762076458a9dbd6849cd393df5bc48f5d60588160161da776105f18d",
          "sha256": "a8565de5d5aaa7ee274e6abb720055c802719f08b3147aa52095f38dfbbae53e",
          "sha1": "2c576deeeb8868d3c9ebee4dad8636f7e5f9979f",
          "md5": "8c3422312b84496e1df8e46b510b1532"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosx64-0.3.8-metadata.jar",
          "url": "miuix-iosx64-0.3.8-metadata.jar",
          "size": 5208,
          "sha512": "e6c1c9cd892ebcf75a08c25a27ae29c09bc61eb1d9b3c6a98a69b2774a5758443ba486aa1c827833daad47bd822b30e42edeb61f4fbc56ff125f90edf28f1d32",
          "sha256": "29bfe2c1d7cc57251e5c04a5d02f398e752f6da4374e23e251df76507c54dbce",
          "sha1": "f1d0eef07ae589c398be1bbc59eaf216ccaa37b3",
          "md5": "1362d87ad6aaa50af2cd1cbb0cc5de9e"
        }
      ]
    }
  ]
}
