{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "haze-metadata.jar",
          "url": "haze-1.6.0-SNAPSHOT.jar",
          "size": 22275,
          "sha512": "9ddfd079e0eb9fd61258bfd2e7e4108d5504c8a43a974ceae569933493331fcd262cead0536fa71170ecbd644268f4093b5641adee95ccda83f1b1b99e7b5aba",
          "sha256": "39ef28fa3104953f5fb3a2d62d6cb544efc251f2a672f8189abb0e4535900825",
          "sha1": "18092af6607654bad4cd494610fcf446a655d290",
          "md5": "dd88fd7075428cfa48d14141e7b4e174"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "haze-kotlin-sources.jar",
          "url": "haze-1.6.0-SNAPSHOT-sources.jar",
          "size": 32516,
          "sha512": "599e2661717ade412ba6d093ff6b8dba6606f8744f43f4bb6687e28830168b8039b7a6c67ada1326672f480c5255ddc6e895364a5dc9e8a2587e092a603fc1fd",
          "sha256": "95deb1f157223120981261d3995da38f2c8f65af8fe1fadfae6c91a7c3c3755e",
          "sha1": "f80f52691dc7e161c1e4d0bcdae755b2919913cc",
          "md5": "92272a9f1782088e0badc1b349a551da"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../haze-android/1.6.0-SNAPSHOT/haze-android-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-android",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../haze-android/1.6.0-SNAPSHOT/haze-android-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-android",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../haze-android/1.6.0-SNAPSHOT/haze-android-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-android",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosarm64/1.6.0-SNAPSHOT/haze-iosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosarm64/1.6.0-SNAPSHOT/haze-iosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosarm64/1.6.0-SNAPSHOT/haze-iosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosarm64/1.6.0-SNAPSHOT/haze-iosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iossimulatorarm64/1.6.0-SNAPSHOT/haze-iossimulatorarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iossimulatorarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iossimulatorarm64/1.6.0-SNAPSHOT/haze-iossimulatorarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iossimulatorarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iossimulatorarm64/1.6.0-SNAPSHOT/haze-iossimulatorarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iossimulatorarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iossimulatorarm64/1.6.0-SNAPSHOT/haze-iossimulatorarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iossimulatorarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosx64/1.6.0-SNAPSHOT/haze-iosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosx64/1.6.0-SNAPSHOT/haze-iosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosx64/1.6.0-SNAPSHOT/haze-iosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosx64/1.6.0-SNAPSHOT/haze-iosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../haze-js/1.6.0-SNAPSHOT/haze-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../haze-js/1.6.0-SNAPSHOT/haze-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../haze-js/1.6.0-SNAPSHOT/haze-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../haze-js/1.6.0-SNAPSHOT/haze-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../haze-jvm/1.6.0-SNAPSHOT/haze-jvm-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-jvm",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../haze-jvm/1.6.0-SNAPSHOT/haze-jvm-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-jvm",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../haze-jvm/1.6.0-SNAPSHOT/haze-jvm-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-jvm",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosarm64/1.6.0-SNAPSHOT/haze-macosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosarm64/1.6.0-SNAPSHOT/haze-macosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosarm64/1.6.0-SNAPSHOT/haze-macosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosarm64/1.6.0-SNAPSHOT/haze-macosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosx64/1.6.0-SNAPSHOT/haze-macosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosx64/1.6.0-SNAPSHOT/haze-macosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosx64/1.6.0-SNAPSHOT/haze-macosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosx64/1.6.0-SNAPSHOT/haze-macosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../haze-wasm-js/1.6.0-SNAPSHOT/haze-wasm-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-wasm-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../haze-wasm-js/1.6.0-SNAPSHOT/haze-wasm-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-wasm-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../haze-wasm-js/1.6.0-SNAPSHOT/haze-wasm-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-wasm-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../haze-wasm-js/1.6.0-SNAPSHOT/haze-wasm-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-wasm-js",
        "version": "1.6.0-SNAPSHOT"
      }
    }
  ]
}
