{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-metadata.jar",
          "url": "haze-1.6.0-SNAPSHOT.jar",
          "size": 25471,
          "sha512": "bea388ae23fa728a4c5604a03ed6a29bc7c3b8bd28cc1aec189fcf3b4a7f972d1600848070e773bc6934d37e4088fee6a5260ce33a0cc30b58581c1dae4a35f5",
          "sha256": "d5d350698f9492257ba9297db6e00a2fdbe35c80588ebfe17a0c45b0a6da5631",
          "sha1": "2c175d0d5aee303646a75fef0e69135ddd88f8fd",
          "md5": "95fefb410560a0975e272d57f3092682"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "haze-kotlin-sources.jar",
          "url": "haze-1.6.0-SNAPSHOT-sources.jar",
          "size": 36509,
          "sha512": "976d09b7883df7c8cfe53a495c1c4fcb9afda75c42b21de763a3b7f68615db44f0781ebf950e94f23a589946c0e6294ae73851603bbe8b90d5120aee7d57979e",
          "sha256": "355c5117655a10a449b2c9597969f4f0a55f45fad40b8771d8b3bd42d1ff24fa",
          "sha1": "b638f3dff46a976cbd827346b84d045942780c3b",
          "md5": "7049ecd1946b281a0bc9042a90313137"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../haze-android/1.6.0-SNAPSHOT/haze-android-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-android",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../haze-android/1.6.0-SNAPSHOT/haze-android-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-android",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../haze-android/1.6.0-SNAPSHOT/haze-android-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-android",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosarm64/1.6.0-SNAPSHOT/haze-iosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosarm64/1.6.0-SNAPSHOT/haze-iosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosarm64/1.6.0-SNAPSHOT/haze-iosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosarm64/1.6.0-SNAPSHOT/haze-iosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iossimulatorarm64/1.6.0-SNAPSHOT/haze-iossimulatorarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iossimulatorarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iossimulatorarm64/1.6.0-SNAPSHOT/haze-iossimulatorarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iossimulatorarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iossimulatorarm64/1.6.0-SNAPSHOT/haze-iossimulatorarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iossimulatorarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iossimulatorarm64/1.6.0-SNAPSHOT/haze-iossimulatorarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iossimulatorarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosx64/1.6.0-SNAPSHOT/haze-iosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosx64/1.6.0-SNAPSHOT/haze-iosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosx64/1.6.0-SNAPSHOT/haze-iosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-iosx64/1.6.0-SNAPSHOT/haze-iosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-iosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../haze-js/1.6.0-SNAPSHOT/haze-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../haze-js/1.6.0-SNAPSHOT/haze-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../haze-js/1.6.0-SNAPSHOT/haze-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../haze-js/1.6.0-SNAPSHOT/haze-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../haze-jvm/1.6.0-SNAPSHOT/haze-jvm-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-jvm",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../haze-jvm/1.6.0-SNAPSHOT/haze-jvm-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-jvm",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../haze-jvm/1.6.0-SNAPSHOT/haze-jvm-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-jvm",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosarm64/1.6.0-SNAPSHOT/haze-macosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosarm64/1.6.0-SNAPSHOT/haze-macosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosarm64/1.6.0-SNAPSHOT/haze-macosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosarm64/1.6.0-SNAPSHOT/haze-macosarm64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosarm64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosx64/1.6.0-SNAPSHOT/haze-macosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosx64/1.6.0-SNAPSHOT/haze-macosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosx64/1.6.0-SNAPSHOT/haze-macosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../haze-macosx64/1.6.0-SNAPSHOT/haze-macosx64-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-macosx64",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../haze-wasm-js/1.6.0-SNAPSHOT/haze-wasm-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-wasm-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../haze-wasm-js/1.6.0-SNAPSHOT/haze-wasm-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-wasm-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../haze-wasm-js/1.6.0-SNAPSHOT/haze-wasm-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-wasm-js",
        "version": "1.6.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../haze-wasm-js/1.6.0-SNAPSHOT/haze-wasm-js-1.6.0-SNAPSHOT.module",
        "group": "dev.chrisbanes.haze",
        "module": "haze-wasm-js",
        "version": "1.6.0-SNAPSHOT"
      }
    }
  ]
}
