{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.4.0/miuix-0.4.0.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.4.0.jar",
          "url": "miuix-desktop-0.4.0.jar",
          "size": 1022393,
          "sha512": "fb77130845d15160f14d7cddfe56d1ccfa5199a71a5955b7501132bfd5567465bcab459c7d193a8f21f0af040137be5a6732974987672ef2100052b7527789c6",
          "sha256": "3ab0a7acbbcd4342b1ff13b5a5747006f7bb0ce1d9e77f5287f31203a610911d",
          "sha1": "560e41533ecfaaf7624c4bce8ff3623651ab276e",
          "md5": "eb62b78144d94f469374ece7719eb329"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.4.0.jar",
          "url": "miuix-desktop-0.4.0.jar",
          "size": 1022393,
          "sha512": "fb77130845d15160f14d7cddfe56d1ccfa5199a71a5955b7501132bfd5567465bcab459c7d193a8f21f0af040137be5a6732974987672ef2100052b7527789c6",
          "sha256": "3ab0a7acbbcd4342b1ff13b5a5747006f7bb0ce1d9e77f5287f31203a610911d",
          "sha1": "560e41533ecfaaf7624c4bce8ff3623651ab276e",
          "md5": "eb62b78144d94f469374ece7719eb329"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "miuix-desktop-0.4.0-sources.jar",
          "url": "miuix-desktop-0.4.0-sources.jar",
          "size": 145974,
          "sha512": "e31611af34270b5bb633822aaeb6fc6ac9060d1334072695dd0f770873cc818ba38c9b96b844dda287a7ee2f395957163b8c62bbd6ab124e8cfc4e7c1aff116e",
          "sha256": "3b172bebc958623bb28dda601703726e6f90ce43fcf967540eaf2865bf5fc850",
          "sha1": "63b360a8140187d6bc19dde9fbc1d346eaab7d78",
          "md5": "f81a250c16c136f4c57e9dabde919fcd"
        }
      ]
    }
  ]
}
