{
  "formatVersion": "1.1",
  "component": {
    "url": "../../haze/1.6.0-SNAPSHOT/haze-1.6.0-SNAPSHOT.module",
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-macosX64Main.klib",
          "url": "haze-macosx64-1.6.0-SNAPSHOT.klib",
          "size": 178238,
          "sha512": "ab3729630860bd793193a1b0b67e062b691c45d85ebae51581093de8d95bb55750b5b69c1beeb863a352f6999524e5092e568ba43eb11985ec7f5e9d2dff7176",
          "sha256": "5fd3200b4d010f34aa6f4eb04230c1615c9cb859ff91fbe5ba90a3db550a8270",
          "sha1": "0ed552c54dc1b510452aca5d7b491168bccf25b8",
          "md5": "46ac50b428a582a699c3362377ffcb36"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "haze-macosx64-sources.jar",
          "url": "haze-macosx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 36509,
          "sha512": "976d09b7883df7c8cfe53a495c1c4fcb9afda75c42b21de763a3b7f68615db44f0781ebf950e94f23a589946c0e6294ae73851603bbe8b90d5120aee7d57979e",
          "sha256": "355c5117655a10a449b2c9597969f4f0a55f45fad40b8771d8b3bd42d1ff24fa",
          "sha1": "b638f3dff46a976cbd827346b84d045942780c3b",
          "md5": "7049ecd1946b281a0bc9042a90313137"
        }
      ]
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze.kotlin_resources.zip",
          "url": "haze-macosx64-1.6.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 316,
          "sha512": "bb8833d38cb4caeabcd5af9e64192f76433bde9f0f7efe4ec76f37c5fae96c011772ae77dc30e62d5b38c910d8c4c980407c84ce939b075b144c8ec23fa8600b",
          "sha256": "e4adc5a8a138055e970787f6b8c546c4a81c2120157040ede73c7c39b3fed9d4",
          "sha1": "7e7f089eb0bfe84f98a978f09d32fe7e5202b3f7",
          "md5": "301706ebe9e6175d0a4c92c5e2591647"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-macosx64-metadata.jar",
          "url": "haze-macosx64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 2856,
          "sha512": "9d3dd5b2f6bb257a494d5ee30c3ec60d336abfde611af92ba10a74230a8e776120fa34248161f09796a18a05c07faa0e76c564fd24e0cb0df8976d80c5b94667",
          "sha256": "0b433b7d919fbcdedaba4cf33fed77bddb85f9977983d7f0c5b93ab8c003e48f",
          "sha1": "be7e35865f63441a6c49551216f5dabcf8f04dd2",
          "md5": "42c48681f2cb3e6944ecaff9114aaefa"
        }
      ]
    }
  ]
}
