{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.7/miuix-0.3.7.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-macosArm64Main-0.3.7.klib",
          "url": "miuix-macosarm64-0.3.7.klib",
          "size": 806550,
          "sha512": "ce9979f898f0887761ee203126edb24bcb2702f9831ef2a08a1771856382a22dce9995642bc3f7a29237754cf1da883bb59e3d25b6c80e6fd4a958dd9f5a7bf9",
          "sha256": "fedc1ae1092012bc543179ca8cd57026c3c057cdaf366fa8af1c0d246b49e6f0",
          "sha1": "12aca742f87ef603c8b1814f8d87e80cc6fe5f8e",
          "md5": "5212ac8d1f3e9c987cb5fe77a5c5b27e"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-macosarm64-0.3.7-sources.jar",
          "url": "miuix-macosarm64-0.3.7-sources.jar",
          "size": 146919,
          "sha512": "e629527854d14523a9826656ea3899d39858e97d72ccc5e743d79fb8b9af4ee3cf1a1f0a96c4118b929126b72050cdf930ce8626b39a22df1e48c841a204c444",
          "sha256": "367de1ce95a080e17cf49cdab826bdbe8a7d2e5ccc62d59412a0662e82e1f954",
          "sha1": "009cb83c71620b22e30f18cd730b360d9d7735a8",
          "md5": "b5e9e6baa011a301eff562c9a83c6ef4"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.7.kotlin_resources.zip",
          "url": "miuix-macosarm64-0.3.7-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "9676158aa2675c1c38455718e299605b3d570b8cd263a5e5e1f2596510a69507c5526a107b53acc34dc3649013d8249a2a39c8b9cfdecc2a7564f31f457d8772",
          "sha256": "756dce847566ee6cbc5b353fd3da90add722984c0467eec04184a51f581da68f",
          "sha1": "0d9ce4bb7584e5d9da852c41f97c700d73f47a5c",
          "md5": "a20f9272b7d6ba44fb9528b8886b3ea3"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-macosarm64-0.3.7-metadata.jar",
          "url": "miuix-macosarm64-0.3.7-metadata.jar",
          "size": 5208,
          "sha512": "4b6f3896cc2d2874af66284ba28c9f0e109df5b8337ccd4c3cd83034b470fb9a62048b9c63e17f9b3d90796fba4b1b413e41ce07708c0ebd39912d1c3082c64c",
          "sha256": "3c5133a5d78ac8e876b1ba961497d265ccebecb671f8cf30d9f7d2d8d59a24b3",
          "sha1": "bd72eec302bef4e8b61b5a385e53a2c39ff46293",
          "md5": "b5541ed153ac67258aaaac08d88d56e3"
        }
      ]
    }
  ]
}
