{
  "formatVersion": "1.1",
  "component": {
    "url": "../../haze/1.6.0-SNAPSHOT/haze-1.6.0-SNAPSHOT.module",
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "haze-wasm-js.klib",
          "url": "haze-wasm-js-1.6.0-SNAPSHOT.klib",
          "size": 158639,
          "sha512": "cb62dca697c846d153da908ed1d0fa2e1f8d2d486532c23102d8efbb6c1a837bbeb2ca317c9f39ca6934543f4f01d7a75c952698dbcdfb40c6e81c2540f81f07",
          "sha256": "8c218c8a508164b6e35e587c0c6750f69087d1c76f874fdc47de2f586da95fe2",
          "sha1": "6d4e4e33b20fc21ac33669313e2e33866395bf93",
          "md5": "9a8b266a09fe89c5b644aebc2626e8b3"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "haze-wasm-js.klib",
          "url": "haze-wasm-js-1.6.0-SNAPSHOT.klib",
          "size": 158639,
          "sha512": "cb62dca697c846d153da908ed1d0fa2e1f8d2d486532c23102d8efbb6c1a837bbeb2ca317c9f39ca6934543f4f01d7a75c952698dbcdfb40c6e81c2540f81f07",
          "sha256": "8c218c8a508164b6e35e587c0c6750f69087d1c76f874fdc47de2f586da95fe2",
          "sha1": "6d4e4e33b20fc21ac33669313e2e33866395bf93",
          "md5": "9a8b266a09fe89c5b644aebc2626e8b3"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "haze-wasm-js-sources.jar",
          "url": "haze-wasm-js-1.6.0-SNAPSHOT-sources.jar",
          "size": 32496,
          "sha512": "a9576f4fd10ea4912045aca685a1b65ad968f39a1a5cc601758d5da2d8d765a3dd523437773f815a31f5cd4c700c4ce06a0318d763fe7a51437d838399db792b",
          "sha256": "d8c8f712687f1d38089e037f6ea22a9e9a4fe3f06561e7a1c4a62aef11992186",
          "sha1": "02f9abd5f4a7dd7fd743f3677767c4c6dec6f0f8",
          "md5": "3b1b617b04192b7da4a748246950d9e5"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "haze.kotlin_resources.zip",
          "url": "haze-wasm-js-1.6.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 316,
          "sha512": "76630aef2cf6dd5df1f2e33c4c7bdd6e04cdb6716b29da915da28bbe01f967e3c97b8d6e6959b5d9a20750c3073a44939df7a4afe8a0e292f90fab55a6dce95d",
          "sha256": "5c3c660373a164db3c3eabd500b79b6acb92ea5b223377888505b0ffbdbde85e",
          "sha1": "9c96efd539cb816d4b79d4a94e578ab4f7b13f3f",
          "md5": "cd9b414e944723c1bc50ad2ff1f6e71c"
        }
      ]
    }
  ]
}
