{
  "formatVersion": "1.1",
  "component": {
    "url": "../../haze/1.6.0-SNAPSHOT/haze-1.6.0-SNAPSHOT.module",
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "haze-wasm-js.klib",
          "url": "haze-wasm-js-1.6.0-SNAPSHOT.klib",
          "size": 178357,
          "sha512": "6a04f836dde2c2cb1e6f2f9d3642977c33c0dc115329b7629b0f99caeb53d86f7988171baaf78959c5adb8f0db3c37be4006b078cfa8384875c835f94965809e",
          "sha256": "8490ab3e49c00d020ff7a50c489cfd6c18d57c564e542bb47d2c0c45b9abffb1",
          "sha1": "4ac7892e4874f021b194409426c0508947041c65",
          "md5": "df88d03b33c97ca614ebce0bc47535eb"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-wasm-js.klib",
          "url": "haze-wasm-js-1.6.0-SNAPSHOT.klib",
          "size": 178357,
          "sha512": "6a04f836dde2c2cb1e6f2f9d3642977c33c0dc115329b7629b0f99caeb53d86f7988171baaf78959c5adb8f0db3c37be4006b078cfa8384875c835f94965809e",
          "sha256": "8490ab3e49c00d020ff7a50c489cfd6c18d57c564e542bb47d2c0c45b9abffb1",
          "sha1": "4ac7892e4874f021b194409426c0508947041c65",
          "md5": "df88d03b33c97ca614ebce0bc47535eb"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "haze-wasm-js-sources.jar",
          "url": "haze-wasm-js-1.6.0-SNAPSHOT-sources.jar",
          "size": 36489,
          "sha512": "1ac1edc37936c73af1769e21b7e4de8c4bc23b3fc87f11c069589bfb0f6d101a90ac253fec07d63939adb91eece6e70f410aec643fe0c44878bd4665e573f767",
          "sha256": "d6aada214a6aa33329390226ba5ca993e40cb84c2c4469f751d9ef8ff1adc391",
          "sha1": "508eb2509549eeb5c69fa0177a75f2babe68e693",
          "md5": "ed1404c8564860e71963dce70a97887f"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze.kotlin_resources.zip",
          "url": "haze-wasm-js-1.6.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 316,
          "sha512": "bb8833d38cb4caeabcd5af9e64192f76433bde9f0f7efe4ec76f37c5fae96c011772ae77dc30e62d5b38c910d8c4c980407c84ce939b075b144c8ec23fa8600b",
          "sha256": "e4adc5a8a138055e970787f6b8c546c4a81c2120157040ede73c7c39b3fed9d4",
          "sha1": "7e7f089eb0bfe84f98a978f09d32fe7e5202b3f7",
          "md5": "301706ebe9e6175d0a4c92c5e2591647"
        }
      ]
    }
  ]
}
