{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.8/miuix-0.3.8.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosArm64Main-0.3.8.klib",
          "url": "miuix-iosarm64-0.3.8.klib",
          "size": 806060,
          "sha512": "e7236b3d365a633842d414870a6bf324b549b8a5911d381254970ef52d90450b56be6d70f9586bc35ed41e04fe75d9146cd662cc5ebbae843252b0616d72ac11",
          "sha256": "de42d1aa43d4b8b0869dabdcebccc722dcf273e73f9a0aaf9a65db4c4734be02",
          "sha1": "a253cc7cacd0a9e9b9a5963beb6046f0ee20824c",
          "md5": "831c5c304a9976e8b0f436089bc0c086"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosarm64-0.3.8-sources.jar",
          "url": "miuix-iosarm64-0.3.8-sources.jar",
          "size": 146785,
          "sha512": "d61aa51049534135ddd8af650cc21f0552d1e9bf455810ff6cccf21b18f7ee9d609cbfc1e03317b3aa0cd86a533da670928ecac1ff6b704addb092efe5894cf6",
          "sha256": "15f870d381f8af41beed2b77c69060a735f3db4df6ed6d4997e02f76de736464",
          "sha1": "da9632b7efa0e356c21a7bb4a2f7d022fb537284",
          "md5": "e6b5d9cd708179f62d8c9344ceb90a4c"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.8.kotlin_resources.zip",
          "url": "miuix-iosarm64-0.3.8-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "8e53c75bf99ac68669e286f3cd6b214620075f841ccd4259279a10849d3e2ae7ed68f9af355b24b4c8718be741480db7341adf12818e0a4bc9c96d10eba5c507",
          "sha256": "861f2d28c50a19e621502803ac6763eafb2fd320fc14d324d31f6fba704d3b6c",
          "sha1": "c05af0b9e4db886b568a354d6a626a4f61490114",
          "md5": "1e6b788668063c9bfcb7afd591d4e86b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosarm64-0.3.8-metadata.jar",
          "url": "miuix-iosarm64-0.3.8-metadata.jar",
          "size": 5208,
          "sha512": "2581b435e5d89006f0d1f0951127c92d83862213baa2b7a0d9eebbf76ae826315c58f56b7df13fa48937b5742a7f6685ecae9543dcac1a99810eb3eee49497e8",
          "sha256": "17c27251865ff21da2d03a22f3214a95b1b817324b7766f5a8247ca0accd1ee4",
          "sha1": "7dcd4bc2cd7ad20bf495aaf4c8535753e7267680",
          "md5": "9d46875f2b8f64980cd03901b2b5c104"
        }
      ]
    }
  ]
}
