{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.4.0/miuix-0.4.0.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.4.0.klib",
          "url": "miuix-wasm-js-0.4.0.klib",
          "size": 803432,
          "sha512": "e52ab2c042c9d5469dbd89b532331ca1bc54b9f9401f1a5088b6da71f1b3d3a43186cf5d93f76799aba914e3a4552387416e8b05a6e71349cd1f2f0675821390",
          "sha256": "eb82ec0f6c06fcc994da6d2f3d808b6f2369b5b2c2787c26c5a9562bf3f552ca",
          "sha1": "88ae120799266e0329fff21316566eadba7f343f",
          "md5": "3bbd57bd3d027d043e993e91db5f416b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.4.0.klib",
          "url": "miuix-wasm-js-0.4.0.klib",
          "size": 803432,
          "sha512": "e52ab2c042c9d5469dbd89b532331ca1bc54b9f9401f1a5088b6da71f1b3d3a43186cf5d93f76799aba914e3a4552387416e8b05a6e71349cd1f2f0675821390",
          "sha256": "eb82ec0f6c06fcc994da6d2f3d808b6f2369b5b2c2787c26c5a9562bf3f552ca",
          "sha1": "88ae120799266e0329fff21316566eadba7f343f",
          "md5": "3bbd57bd3d027d043e993e91db5f416b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "miuix-wasm-js-0.4.0-sources.jar",
          "url": "miuix-wasm-js-0.4.0-sources.jar",
          "size": 145963,
          "sha512": "0d08b2d093aaa67ff09b98493a8fa6c0c23591fb4a864df4e484fd6238e8bd57c9896ff49d6ca1e0f34080ab3330f85404504f81a6a43bd3b54a690615b1c13b",
          "sha256": "47576ad565239b8723e9f603c9f2ee2b642f57953fe434e5d2db85c96f3c98b5",
          "sha1": "d7c146f367020ffc3a82f07322c7bbf16a5300ba",
          "md5": "6c65f8bc2902a5126697b792b51ef712"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.4.0.kotlin_resources.zip",
          "url": "miuix-wasm-js-0.4.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "d2fcb171ba51699a0e6b08b5bdb7e286edb71c882ad7d2747263d3778e66040a1b164f8e9c79e1cc46855cc3d091cd72bfa4218db0c0ce1acd773f4395451270",
          "sha256": "f3c5fca29500a3dd7919a36be1459cc4c9c46bc815ef4b988bb0fae585dd70ac",
          "sha1": "7ea352e6b4be4f1f273d30da8bfadf5e853345d3",
          "md5": "8dc3c74d8bfaa62947980608e04c6c24"
        }
      ]
    }
  ]
}
