{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.4.0/miuix-0.4.0.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-macosX64Main-0.4.0.klib",
          "url": "miuix-macosx64-0.4.0.klib",
          "size": 800858,
          "sha512": "b7fad8660e12e8c070e6a2fb705db96daa50be2e243cae05a250bc38128d619db9e8964792aa00a2a1b7062ec4116f3ac5fac4a3f27665be891d861506e01c2c",
          "sha256": "f610b8453359c88e99a7adddac2ae9ae9e0df010113715b02fabf7e63710c305",
          "sha1": "93d1b31b2854d5d918c7756d8c06f7e327890281",
          "md5": "7fd4f7fbd1bcccc19199efa9d9cde2ae"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-macosx64-0.4.0-sources.jar",
          "url": "miuix-macosx64-0.4.0-sources.jar",
          "size": 146644,
          "sha512": "8be48d72a04ee8826d850d4b7810592046b6f917209b3d89560ac5c88467c80ced347a4148c445a1bcf1ca771a3bbe85f42829f66b12cc36137192f871e66590",
          "sha256": "2071299842ab5879d8edeae52688ad9a99a9c87cfefb9aacd807bc5f7fe98dd5",
          "sha1": "fc583f4675cf2b77941c78ea4429358d1b3e9857",
          "md5": "e67f50069c3e2b66b89c2f8d20483c85"
        }
      ]
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.4.0.kotlin_resources.zip",
          "url": "miuix-macosx64-0.4.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "274e199fe540ea8750d062b8b400c7200e8f333fe9a5099f62adfd1cbe93a8bd2f3d28ffa99acffd629c5f30a8f4d070e758761cb84e63ae101e1dd06a723c8a",
          "sha256": "86d524f317912574232d5aa467ff250bb483a0d076e49b074899866d5dd0fddf",
          "sha1": "abdd20e20e5e0a38f19dd0784e7782ab7ddf16ca",
          "md5": "348af95af502bda9237f87d23d3a1254"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-macosx64-0.4.0-metadata.jar",
          "url": "miuix-macosx64-0.4.0-metadata.jar",
          "size": 5208,
          "sha512": "0aae9dbb5a3c78c2ca257a8d0dd092f61699376f6f1b65cf5a738890698adfa0286e6c168bb4ca40622b255a9db81eb4d945379920d08ae075d6ab9ad6175dde",
          "sha256": "3f8c79b9d2ff8391c87d62bd83126ec2d006be628276c01029231f7bcc4b0b6c",
          "sha1": "0078f201d5794a419b9561e3369b072f158cd005",
          "md5": "12f14d0d917f46bd4c8f618f8ea1ed65"
        }
      ]
    }
  ]
}
