{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.4.0/miuix-0.4.0.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosX64Main-0.4.0.klib",
          "url": "miuix-iosx64-0.4.0.klib",
          "size": 800327,
          "sha512": "5bbe9e72a68e1492549fea1172fce00c420c1c55173271caf185444d36bb35a3ae9817c519a0d2f53d0c782d90279d86525a1d33cf3c7db3f58823c106f9d9f7",
          "sha256": "8c60ceb0793548945ef7ed9652d670b40c90938a7b168ad075752ab01a485c1f",
          "sha1": "f9fb9e4e81923bebb479b2f7905b30e23b18b459",
          "md5": "ea81930dfb9dd34e89628c167b1df1b6"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosx64-0.4.0-sources.jar",
          "url": "miuix-iosx64-0.4.0-sources.jar",
          "size": 146506,
          "sha512": "1e950178a34cebd2ca5b6798dc243d8b5f6d68b1c7e769ce29d2225514620e2f185cd5df12030fb90eb1c4e0a6c21aa5206c18b5f8758bb914ba19a5586f0acb",
          "sha256": "c99dc73d67c335133ae5a2b61cbbab33f2a1994eb9a4070997014137f4853770",
          "sha1": "21d01a763871d02f3556410caaa2271ff25c76c5",
          "md5": "c0ad21ee8d8930a5145a1f82ccdcd175"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.4.0.kotlin_resources.zip",
          "url": "miuix-iosx64-0.4.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "25053013a1d857e1c365481c53dc4c98e568fadf2c9741998373924728d27c5d30e41bb83d5d19d527a87860e3ed8b9a8c4ce459ea435ae77269057a5f3f49ca",
          "sha256": "5057b79eff1e8be75e17f1f618d6fc5e25fd3799afadeda58b2932b09c1cf372",
          "sha1": "58b17896ad08c5387b2c3ac8eebcebc883d022f2",
          "md5": "4f5c44eb6cf3413301524912cd1fd5a9"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosx64-0.4.0-metadata.jar",
          "url": "miuix-iosx64-0.4.0-metadata.jar",
          "size": 5208,
          "sha512": "785892436f6e7a5e62ef35879155e26824627a1ab5b48f2b5bf61c04797df1a5c086ed98a2d88a72011cdeafe389c78d0987bf1087c47b52ee53334ca20df20d",
          "sha256": "bb1d0180897d1ef44725f091f5ae819098fb72ef3bd68e67982480fb56f7f5ba",
          "sha1": "a6fb52565dfccf0f076fa1bc34e3ed8c5b83f483",
          "md5": "ca1042960255a903090600b55fb518cb"
        }
      ]
    }
  ]
}
