{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.7/miuix-0.3.7.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosX64Main-0.3.7.klib",
          "url": "miuix-iosx64-0.3.7.klib",
          "size": 806000,
          "sha512": "5396dc5764f097288b06197c5620271398f7a344fdd1e924d19c7a11ed7876cbb2a22a1b96f6620966c9d17d50379f2d3a2f641d077a0578376fed39c153aeea",
          "sha256": "b9f68e5f37372ff589f286dcf900bebc650d4d5ed2ae8cf76f7d2d2034592134",
          "sha1": "2c266f472a085bb140522f03dcbbf529309775f9",
          "md5": "4d626f969416321c6ec4ebd2d4463ddf"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosx64-0.3.7-sources.jar",
          "url": "miuix-iosx64-0.3.7-sources.jar",
          "size": 146745,
          "sha512": "d252ee80af4c6d6c31a975a9809567b7a98bc86f823dcba0aec51348e4aadb8cae52870cd045aa38852e0764320ce3bd9433e74577ce76c03fa6c3ca5136f680",
          "sha256": "2deab2eea1e28646e6fb2645bdac9e1aee6fc52fe2e3193b5fba9076ade0a42f",
          "sha1": "5f016771e8ee7ce55317b4b6d7f5b067b3b2cb51",
          "md5": "b7c7a90bcfb0454da976fb9a401c86e8"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.7.kotlin_resources.zip",
          "url": "miuix-iosx64-0.3.7-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "8d99c7f0329300f5d79d73b0904fcfb66f484106736d99e4a9a1b94f9be6ac890f41708304eafd3511eb09c9d9e6dbff036519e3522936d0682d1e6086b6b73d",
          "sha256": "04ef0b75dd39d1097232f5fc89dbadd8847792578019421cad7c00ec991a136f",
          "sha1": "bcd4600509be513fb986eeb5a1afe6406a96855a",
          "md5": "cae0d0a11d5b694f62eb6c151738c016"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosx64-0.3.7-metadata.jar",
          "url": "miuix-iosx64-0.3.7-metadata.jar",
          "size": 5208,
          "sha512": "7a57e744b7df0af6dcc6ad8c9e3edbc0bcf76fbb0d28d006335f632ab1379159f8d47fa1bab6bebfccbf707c9879542d72a92284a8dad31d30dc7584c67736ac",
          "sha256": "f77b608013f2de134e7c8926b003750354c0ce41aadaa93903e8f826e8989343",
          "sha1": "60bc6e7483079fb85aff0b0d8b513897a8e04b13",
          "md5": "3176faab60238514f0ec80105fb1d991"
        }
      ]
    }
  ]
}
