{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.6/miuix-0.3.6.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosSimulatorArm64Main-0.3.6.klib",
          "url": "miuix-iossimulatorarm64-0.3.6.klib",
          "size": 813571,
          "sha512": "e7fd1b63767d86c58b06d522798d1f42f6c14110f6e919245ca0c0723fbec0fcb600f3f0804935f9e4950d70a769f156ea3ef8059afb19d7cf029bc533eba218",
          "sha256": "32eece96512598586ed6c1dfad4e188b6a9861de5c8abee3bee1cc50c582ffdc",
          "sha1": "8bff76e2b697e6b9c52fedd37a129540f5a2ca78",
          "md5": "730b47995513e534596f7312aca8a4c3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iossimulatorarm64-0.3.6-sources.jar",
          "url": "miuix-iossimulatorarm64-0.3.6-sources.jar",
          "size": 147701,
          "sha512": "c14e587375c62dd82b90b077b39a6ec7b5ab5c54da8fd4bc1c16cf5debed230b16c41f8aa86791f3b2188a9c6ac5bb777f540310988bf2d88899b753bef57bc3",
          "sha256": "0c60eb4f7125f4f9cf94ad9a1fa94791724fb4e99b4d8bd98d9013f99600660f",
          "sha1": "7f78d5add35b43dbc87b0739553540682bf60ce1",
          "md5": "c5049a4b3de20df51877f9643ebc6481"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.6.kotlin_resources.zip",
          "url": "miuix-iossimulatorarm64-0.3.6-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "e5e77c91d25ea803302f3f41ea3f71a6222abeec0ad0071693b346399bf90762ab8fc50c4e182052a5c375841db6ac25cf583004bbfbe328546b81b23e1a9fba",
          "sha256": "904a20b7e85b0bab712cc3c44fa9037e6f7b38ac2eca2df51b698c0b769639fa",
          "sha1": "95cf63b8a71639af486ef78ef6519de8cf4fcedc",
          "md5": "6c352e228f3146c41e66708e08e5e45f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iossimulatorarm64-0.3.6-metadata.jar",
          "url": "miuix-iossimulatorarm64-0.3.6-metadata.jar",
          "size": 5209,
          "sha512": "c9366a4d54ed7714c2898f19bb401c8d3ce78c8ef62bc03c4f56676173fd72e26aa4613b62c1c80a1ce0c9d43c718d7ae11f7d85f7c4433c93a01f8fb8f9216f",
          "sha256": "95d175e3456c41e3c20fe878bec05b5b533ae0c9ece078797c1953b0adaa5272",
          "sha1": "27920686beb7c0af782f191ba250945ad70f675d",
          "md5": "ca649a8cccbb4fec1d216d81dfd61d93"
        }
      ]
    }
  ]
}
