{
  "formatVersion": "1.1",
  "component": {
    "url": "../../haze/1.6.0-SNAPSHOT/haze-1.6.0-SNAPSHOT.module",
    "group": "dev.chrisbanes.haze",
    "module": "haze",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "haze-js.klib",
          "url": "haze-js-1.6.0-SNAPSHOT.klib",
          "size": 3487513,
          "sha512": "6850e4c1a02b038f9b5a06bb9eb43a417360b5f66514a48e0b9f916a6bded2e4ee8950790ee3d5191acffa176dacc46632b1af463a3e4c87d06735017f50c986",
          "sha256": "1b1a71f98168efd1de0d26f6ed60ac90244522f813919f7bec454307b92c79bc",
          "sha1": "fcd5439b2d0c000d590901ed00abfc32fbc1f7e5",
          "md5": "8e867f912e46d181ce5e58d473b94cb1"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze-js.klib",
          "url": "haze-js-1.6.0-SNAPSHOT.klib",
          "size": 3487513,
          "sha512": "6850e4c1a02b038f9b5a06bb9eb43a417360b5f66514a48e0b9f916a6bded2e4ee8950790ee3d5191acffa176dacc46632b1af463a3e4c87d06735017f50c986",
          "sha256": "1b1a71f98168efd1de0d26f6ed60ac90244522f813919f7bec454307b92c79bc",
          "sha1": "fcd5439b2d0c000d590901ed00abfc32fbc1f7e5",
          "md5": "8e867f912e46d181ce5e58d473b94cb1"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "haze-js-sources.jar",
          "url": "haze-js-1.6.0-SNAPSHOT-sources.jar",
          "size": 36407,
          "sha512": "3489a4dc1df7eafedbd97586e96eb998fe4ffda471e6a111d87a31fb773dcebc5b8592d34a35b6118ac951c4e7db1e485fe99bc482e6d18b48ea60f6431561c4",
          "sha256": "eaf2cb55dcf070155dae37467586794ec1440edc5fa31258a53afab946c90f40",
          "sha1": "f7de6a41352fa7ae9301c1c344d2196316e0c189",
          "md5": "440d9cb34d10f145007f3f9d627c2916"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "haze.kotlin_resources.zip",
          "url": "haze-js-1.6.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 316,
          "sha512": "bf7fe1a2682dc22ca4b9262d0e29fb1cfb1f2e2c89a4f8e6ecd2034dc8b3491a964969df67c418ff6be0840719d24bce61ea6bd757cc898f54add7adac8f2818",
          "sha256": "f28247f44cce1ca5c28d277dc0996346957424520c29b9ce92cb4daa3f96223a",
          "sha1": "f520652ad156e4a8f824b40079cdabf9abc07caa",
          "md5": "57305aeee4cf6e1a1b4b5d85ad6be641"
        }
      ]
    }
  ]
}
