{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.7/miuix-0.3.7.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosArm64Main-0.3.7.klib",
          "url": "miuix-iosarm64-0.3.7.klib",
          "size": 806024,
          "sha512": "1892b003923881a2d5a8a8f02d0d2a2e6dba5664d88d833c436c023dc69c18337e0b9e1d275284463d9dd66d91a7bf04f287b22f1c7ec366e05f7c11b2b6a220",
          "sha256": "cb257637038bced0f0a259c3cda25b09be92a450faa5831a778b42cfe05c44bb",
          "sha1": "6dd02f4f276f867ba03cd7e13b8a53b2762711dc",
          "md5": "3bee175247eccf8c7af08734d326fdbb"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosarm64-0.3.7-sources.jar",
          "url": "miuix-iosarm64-0.3.7-sources.jar",
          "size": 146781,
          "sha512": "18b271a6310f1f7ef65ec39370e9d5817f059c8b16c54778dbb2d0601dce481e5a761d66cba99caba9e271f4a16112da661a0ee81ba1f7acde49d12bedc010eb",
          "sha256": "9034bf4ed4a638d280d976669a4f1e57b8004d6a40aa05506712e9534dc173cc",
          "sha1": "4956ba22c4581d459759517e98e8643aeb4e0036",
          "md5": "3d3e797abd8d28c3279c436cb94b2078"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.7.kotlin_resources.zip",
          "url": "miuix-iosarm64-0.3.7-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "ce809536779dc1f21778e979db7f4d4ebab08c90029474e7998bf042f39490324dd240ed85fe54d388401605559d1d6daa9d4edddcf6908e11548f927e53d44a",
          "sha256": "b751f51bbd2c87ac23c88bd4c075ca3db4881f23bcd3b991a080857f048cab26",
          "sha1": "f03294a539cbe0d7bba1e8e321f1bf64db3df648",
          "md5": "f48cea99788f5b7300ca3013caefe5e0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosarm64-0.3.7-metadata.jar",
          "url": "miuix-iosarm64-0.3.7-metadata.jar",
          "size": 5208,
          "sha512": "2c824d996012b3d0eaa22ea37d1d25eee9d3d85761a8b9802bc9f8ea59abccb4675e8b00b5d3200a254bf312e184fc8086317a079ddb9597db50b28feeb456e8",
          "sha256": "a883c4d76d54c162dc402c1fdce36d7905f760a59b3322ba696176248659e41a",
          "sha1": "78ccf81107e36758d02cdaf0515c682db0780999",
          "md5": "1ac596e5186919a1c0a8bf3dc986a45c"
        }
      ]
    }
  ]
}
