{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.6/miuix-0.3.6.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosX64Main-0.3.6.klib",
          "url": "miuix-iosx64-0.3.6.klib",
          "size": 813454,
          "sha512": "edf33f58f86933082cd7a838769d6862eca23930698d66c2fe930a126c223f0c0b138c1a09da0385911922c35721ec0e10db07e440ba160cb256e10a62844810",
          "sha256": "dfb392f1f0ab01102a143a035d0bd266b28f60a933f84325afc4e4ca8fb0ae09",
          "sha1": "9ebf430c843efb7ecb19f28641d298f6722eaf5f",
          "md5": "93e0c01cdcf8176fc546bb02a39798ee"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosx64-0.3.6-sources.jar",
          "url": "miuix-iosx64-0.3.6-sources.jar",
          "size": 147503,
          "sha512": "3dac0cf3fd42f3024a8a7479f84c84442aeb0fa5c9bb64b640ad4788eb00ac2eaf557ee4f74644127bfbe86d5353ff4270466d2156afcf30c1110111482288e1",
          "sha256": "b710193107190e7f1d3e2e57c6f5940751e0a9c21187dd8cbb2aa22d89f0b8a7",
          "sha1": "0effdd25a59c023979fa4f8f09f1fc9abf4614dd",
          "md5": "b6014aa41980d9458673e4fe2994d0fa"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.6.kotlin_resources.zip",
          "url": "miuix-iosx64-0.3.6-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "340cb00abd3b775484bdb0bce760fa49022c9d05ae48428f2e69896b6bafa0742c31d55f0ac7f92852cbde43e85286c729344eea4a97a35df62176b531e3c9e9",
          "sha256": "706f3b7decbcc5f0dff473f672748f6a774a75a6dadfe778ebac72eabaea2c17",
          "sha1": "95fe26044e03be877e7c8f74cda2132f48a6e855",
          "md5": "8f77885b076fae0a6d67f48b44653171"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosx64-0.3.6-metadata.jar",
          "url": "miuix-iosx64-0.3.6-metadata.jar",
          "size": 5209,
          "sha512": "a93e77ee8441bf522b20f44a42cfb4c06fa5279bf465009cc5eb8a45986e78109b37e79da07a6e6e03c7f039fd8fc0c6a05f44560a84b78b4f9c32b73f7c9d70",
          "sha256": "64006471f34b5e2806f2fbf439295294460c3b663143dc7a3a265da9328b258e",
          "sha1": "b126d85ae0116b3b6b407f9ba7cc923a026b7ce7",
          "md5": "98d7d5c8439dca13b1720e2ea398bd83"
        }
      ]
    }
  ]
}
