{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.3.6/miuix-0.3.6.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-js-0.3.6.klib",
          "url": "miuix-js-0.3.6.klib",
          "size": 4241328,
          "sha512": "a2d76d688d101cb0e5fbe93dc2355fbb42e0a25274327574020acbfa77f8fa88d6a7e44372c8345457714e3f2ec4672207501a463d6f9e3842c10f693135c1d5",
          "sha256": "efc306dec5064f08650664176a878de999f4461b525d398810e4e17923d9d239",
          "sha1": "c2f017f3ff6cf508b5e46f7e0348be23514986ed",
          "md5": "e8af008c708eeb2e8c7f34c8914ab5f1"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-js-0.3.6.klib",
          "url": "miuix-js-0.3.6.klib",
          "size": 4241328,
          "sha512": "a2d76d688d101cb0e5fbe93dc2355fbb42e0a25274327574020acbfa77f8fa88d6a7e44372c8345457714e3f2ec4672207501a463d6f9e3842c10f693135c1d5",
          "sha256": "efc306dec5064f08650664176a878de999f4461b525d398810e4e17923d9d239",
          "sha1": "c2f017f3ff6cf508b5e46f7e0348be23514986ed",
          "md5": "e8af008c708eeb2e8c7f34c8914ab5f1"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "miuix-js-0.3.6-sources.jar",
          "url": "miuix-js-0.3.6-sources.jar",
          "size": 146854,
          "sha512": "b23a95cc994e3a3ff98b9ca679bb781a5f1921e87751742b2119dd700832605f9c70cd079566aa2348a5fb54ae53064708a6b3425cadc35f85542f619a7c36c1",
          "sha256": "e1305055262522cac7bb5dab0151f3025f61300b03d9d557f37b56cbb46c19cb",
          "sha1": "0316008f2b705322d223a2523aa91a4f7f00d1c6",
          "md5": "99a936b8918f59e3c31e93256daddd3c"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.3.6.kotlin_resources.zip",
          "url": "miuix-js-0.3.6-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "5b87b0425b0fd8ac803ef371bbf3f09e50dfe59ab1a7eb75a4a3f7e037b0315d7d7f4e37d39171e9ff0531e5daba72dea814892e6d58de5d600d9c80e3d8894e",
          "sha256": "5a1d7fcd4959d75efb666bc3b28320d03d37f8b45d8aa5bd747b8c62a880274e",
          "sha1": "a1c87dd8531167407b9667269b26a2dd07ad3f99",
          "md5": "abf700fb3f9cad083341177f03e0c7ef"
        }
      ]
    }
  ]
}
